# -*- coding: utf-8 -*-
"""Untitled51.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14FgyLGzHvITmNvF9KPyOTfFZN-kLsJ3Y
"""



"""# Task
Analyze retail sales data to identify trends, seasonal patterns, and key performance metrics using the dataset "/content/Online Retail.xlsx".

## Load the dataset

### Subtask:
Load the data from the '/content/Online Retail.xlsx' file into a pandas DataFrame.

**Reasoning**:
Import the pandas library and load the data from the excel file into a DataFrame.
"""

import pandas as pd

df = pd.read_excel('/content/Online Retail.xlsx')

"""**Reasoning**:
Display the first few rows of the DataFrame to verify the data loading.


"""

display(df.head())

"""## Preprocess the data

### Subtask:
Handle missing values, convert data types (especially date fields), and clean the data for analysis.

**Reasoning**:
Check for missing values and handle them by dropping rows with missing 'CustomerID'. Also, convert 'InvoiceDate' to datetime objects and filter out rows with non-positive 'Quantity' and 'UnitPrice'. Finally, display the shape of the cleaned DataFrame.
"""

print("Missing values before handling:")
print(df.isnull().sum())

df.dropna(subset=['CustomerID'], inplace=True)

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

df = df[df['Quantity'] > 0]
df = df[df['UnitPrice'] > 0]

print("\nShape of the DataFrame after preprocessing:")
print(df.shape)

"""## Exploratory data analysis (eda)

### Subtask:
Analyze sales trends over time and across product categories. This may involve grouping, aggregation, and calculating key metrics.

**Reasoning**:
Calculate the total sale amount, group by date to get daily sales, group by description to get best-selling products, and sort the best-selling products.
"""

df['TotalPrice'] = df['Quantity'] * df['UnitPrice']
daily_sales_df = df.groupby('InvoiceDate')['TotalPrice'].sum().reset_index()
best_selling_products_df = df.groupby('Description')['Quantity'].sum().reset_index()
best_selling_products_df = best_selling_products_df.sort_values(by='Quantity', ascending=False)
display(daily_sales_df.head())
display(best_selling_products_df.head())

"""## Visualize data

### Subtask:
Create visualizations such as line charts, bar charts, or scatter plots to highlight trends, seasonal patterns, and other insights.

**Reasoning**:
Create a line plot for daily sales and a bar chart for the top 10 best-selling products to visualize trends and insights.
"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15, 6))
sns.lineplot(data=daily_sales_df, x='InvoiceDate', y='TotalPrice')
plt.title('Daily Sales Trend Over Time')
plt.xlabel('Date')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(15, 6))
sns.barplot(data=best_selling_products_df.head(10), x='Quantity', y='Description', palette='viridis')
plt.title('Top 10 Best-Selling Products by Quantity')
plt.xlabel('Quantity Sold')
plt.ylabel('Product Description')
plt.tight_layout()
plt.show()

"""## Summarize insights

### Subtask:
Provide a brief report summarizing the actionable insights derived from the analysis and visualizations.

**Reasoning**:
Write a summary report based on the visualizations and analysis performed in the previous steps.
"""

report = """
Retail Sales Analysis Report

Daily Sales Trend:
The daily sales trend line plot shows significant fluctuations throughout the analyzed period. There is a noticeable upward trend in sales towards the end of the year, likely indicating a seasonal peak, potentially due to holiday shopping. There are also sharp drops in sales, which could correspond to weekends, public holidays, or other non-selling periods. Overall, the sales show a clear seasonal pattern with a strong performance in the later months.

Top 10 Best-Selling Products:
The bar plot of the top 10 best-selling products reveals the most popular items by quantity sold. The products and their relative popularity are as follows:
- PAPER CRAFT, LITTLE BIRDIE
- MEDIUM CERAMIC TOP STORAGE JAR
- WORLD WAR 2 GLIDERS ASSTD DESIGNS
- JUMBO BAG RED RETROSPOT
- WHITE HANGING HEART T-LIGHT HOLDER
- ... (and the remaining top 10 products)

Actionable Insights:
Based on the analysis, here are some actionable insights:
- Inventory Management: Stock up on the top-selling products, especially in anticipation of the peak sales season towards the end of the year. Monitor inventory levels closely for these popular items to avoid stockouts.
- Marketing Strategies: Promote the best-selling products through marketing campaigns. Consider bundling popular items or offering promotions during peak seasons.
- Seasonal Planning: The clear seasonal trend indicates the importance of planning for increased demand in the later months of the year. This includes staffing, inventory, and marketing efforts.
- Further Analysis: Investigate the reasons for the sharp drops in daily sales to understand potential non-selling days or other factors impacting sales. Analyze regional sales data to identify geographical trends and tailor strategies accordingly.
"""

print(report)

"""## Summary:

### Data Analysis Key Findings
*   The dataset initially contained missing values in the 'Description' and 'CustomerID' columns.
*   After preprocessing, which included removing rows with missing 'CustomerID', filtering for positive 'Quantity' and 'UnitPrice', and converting 'InvoiceDate' to datetime, the DataFrame size was reduced from an initial size to (397884, 8).
*   The analysis successfully calculated daily total sales and identified the top 10 best-selling products by quantity.
*   Visualizations confirmed a significant upward trend in sales towards the end of the year, indicating a seasonal peak.
*   Sharp drops in daily sales were observed, potentially corresponding to non-selling periods like weekends or holidays.
*   The top 10 best-selling products include items like "PAPER CRAFT, LITTLE BIRDIE," "MEDIUM CERAMIC TOP STORAGE JAR," and "WORLD WAR 2 GLIDERS ASSTD DESIGNS."

### Insights or Next Steps
*   Implement inventory management strategies to stock up on top-selling products, especially in anticipation of the seasonal peak.
*   Develop targeted marketing campaigns promoting best-selling products and consider seasonal promotions.

"""